### ISSUE TITLE
 ?do not connect to osm retrieving "belgium-latest.osm.pbf"

### ISSUE THREAD

**Issue by Jakkajakka** [itinero/streetscan-planner#3]
Is it possible that the latest version do not connect to osm retrieving belgium-latest.osm.pbf
command line stops after few minutes ....
Is it necessary that the publish folder stays nested in all those empty folders ?
\src\StreetScan.Planner\bin\release\netcoreapp3.1\win10-x64
Is it possible to adapt the "car file" to "bicycle" routing, where to find this file?.

os=win 10

**Comment by xivk** [comment]
This should fix this issue: 

https://github.com/itinero/streetscan-planner/commit/a2733a41229cdaaa3aef8ed5ccfc6cf90ae66642
